-- ============================================================
-- SpendWise — Bulk Data Import (v2)
-- Loads TSV files generated by generate.py
-- Budgets are already in DB (inserted directly by generate.py)
--
-- Run from project root — choose ONE method:
--   Docker PowerShell (easiest):
--     .\ml\seeding\load.ps1
--   Docker bash:
--     bash ml/seeding/load.sh
--   Host psql:
--     cp ml/seeding/output/*.tsv /tmp/seeding/
--     psql -h 127.0.0.1 -p 5435 -U spendwise -d spendwise -f ml/seeding/import.sql
--   PowerShell:
--     docker cp ml/seeding/output/. spendwise-db:/tmp/seeding/
--     Get-Content ml/seeding/import.sql | docker exec -i spendwise-db psql -U spendwise -d spendwise
-- ============================================================

BEGIN;

-- ── Disable triggers (requires superuser or table owner) ──────────────────
ALTER TABLE expense_splits DISABLE TRIGGER ALL;
ALTER TABLE expenses       DISABLE TRIGGER ALL;

-- ── Wipe existing data (child first to respect FK order) ──────────────────
TRUNCATE expense_splits, expenses RESTART IDENTITY CASCADE;

-- ── Load expenses ─────────────────────────────────────────────────────────
\copy expenses (id, context_id, category_id, created_by, amount, expense_date, note, split_type, is_settled, created_at, updated_at, deleted_at) FROM '/tmp/seeding/expenses.tsv' WITH (FORMAT text, DELIMITER E'\t', NULL 'NULL');

-- ── Load expense_splits ───────────────────────────────────────────────────
\copy expense_splits (id, expense_id, user_id, share_amount, percentage, created_at, updated_at) FROM '/tmp/seeding/expense_splits.tsv' WITH (FORMAT text, DELIMITER E'\t', NULL 'NULL');

-- ── Re-enable triggers ────────────────────────────────────────────────────
ALTER TABLE expenses       ENABLE TRIGGER ALL;
ALTER TABLE expense_splits ENABLE TRIGGER ALL;

COMMIT;

-- ── Post-load maintenance (must be outside transaction) ───────────────────
VACUUM ANALYZE expenses;
VACUUM ANALYZE expense_splits;

-- ── Verification ──────────────────────────────────────────────────────────
SELECT 'expenses'       AS tbl, COUNT(*) AS row_count FROM expenses
UNION ALL
SELECT 'expense_splits' AS tbl, COUNT(*) AS row_count FROM expense_splits
UNION ALL
SELECT 'budgets'        AS tbl, COUNT(*) AS row_count FROM budgets;
