services:
    postgres:
        image: postgres:17-alpine
        container_name: spendwise-db
        restart: unless-stopped
        ports:
            - "5435:5432"
        environment:
            POSTGRES_DB: spendwise
            POSTGRES_USER: spendwise
            POSTGRES_PASSWORD: spendwise
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
